name: hello-world

#Events 

on: 
  push: 
    branches:
      -main
pull_request:
  branches:
    -main
workflow_dispatch:

# Woorkflow / Jobs

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello World"
        shell: bash